### PR TITLE
StRetep/A Central hub for accessing all features

### PR DESCRIPTION
**Pull request by Retep-dev**
Create a central hub that contains link to all other pages 
Screenshot (14)
@Realwale 
@olusolaa 
@toluwase1

### CODE REVIEW

**Comment by Realwale** [comment]
You didn't follow the correct naming format for your branch. You should provide enough information about your task.

**Comment by olusolaa** [comment]
Nice work, @Retep-dev

**Comment by olusolaa** [comment]
I ran the code and got an empty screen with this error. Please fix it and resolve the merge conflict.

image

image

**Comment by olusolaa** [comment]
Let's complete this today please.

**Comment by olusolaa** [comment]
@Retep-dev

**Comment by Retep-dev** [comment]
@olusolaa Noted.. How do we go about resolving this?

**Comment by Retep-dev** [comment]
I am working on resolving the conflicts 

I apologise for the delay

**Pull request merged**
